### ISSUE TITLE
Unrolling from loss of speed doesn't reset is_rolling flag.

### ISSUE THREAD

**Issue by RobTF** [marmitoTH/GoSonic2D#1]
If you run and press down to roll, if the character then unrolls due to the X velocity being < `unroll_speed` the `is_rolling` flag doesn't get unset. This prevents the ground angle being processed properly as well as leaves rolling friction adjustments in place until the character jumps.

**Comment by marmitoTH** [comment]
I don't know how I never noticed that! lol

It's fixed now, thanks! 👍
