### ISSUE TITLE
Make Loops

### ISSUE THREAD

**Issue by partisani** [marmitoTH/GoSonic2D#3]
How do i make any loops?

**Comment by RedSnowStudioOfficial** [comment]
> How do i make any loops?

See how loops are made in this Marmito project, this method also works in this

https://github.com/marmitoTH/Godot-Sonic-Physics

**Comment by partisani** [comment]
i even downloaded and tried, but didn't got anything

**Comment by marmitoTH** [comment]
I added loops to the example scene. 👍
